### ISSUE TITLE
milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [data301-2020-winter1/course-project-solo_122#1]
Hi,

here are a few suggestions:

- [x] you should write your observations and arguments in a markup block rather than code comment.

- [x] when you do count plots it's best to sort the data in your count plot 

- [x] you should write your research questions and explain for each analysis and chart you do, how that helps you in achieving your results

- [x] other analysis that you can to is to do average salary based on level of education , marital status , sex , race , work class and etc.

- [x] you should also show on your charts, different age groups rather than every specific age
